name: cuckoo
description: "Cuckoo Flutter Project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  persistent_bottom_nav_bar: ^5.0.2
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  path_provider: ^2.1.3
  flutter_local_notifications: ^17.0.1
  flutter_native_splash: ^2.4.0
  go_router: ^13.2.4
  font_awesome_flutter: ^10.7.0
  connectivity_plus: ^6.0.2
  flutter_animate: ^4.5.0
  toggle_switch: ^2.3.0
  flutter_svg: ^2.0.10+1
  infinite_scroll_pagination: ^4.0.0
  flutter_slidable: ^3.1.0
  url_launcher: ^6.2.6
  uni_links: ^0.5.1
  fluttertoast: ^8.2.5
  dio: ^5.4.2
  json_annotation: ^4.8.1
  flutter:
    sdk: flutter
  collection: ^1.18.0
  sticky_headers: ^0.3.0+2
  intl: ^0.19.0

dev_dependencies:
  json_model: ^1.0.0
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter-Black.ttf
          weight: 900
  assets:
    - images/illus/
    - images/illus/dark/